name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: |
          dotnet restore .\IntegrationMod\src\IntegrationMod.csproj

      - name: Build
        run: |
          dotnet build .\IntegrationMod\src\IntegrationMod.csproj -c Release --no-restore

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: IntegrationMod-build
          path: |
            IntegrationMod\src\bin\Release\**\IntegrationMod.dll
            IntegrationMod\src\bin\Release\**\IntegrationMod.pdb
            IntegrationMod\src\bin\Release\**\IntegrationMod.deps.json